<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Catatan Harian</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark"
     style="background: linear-gradient(90deg,#4f46e5,#6366f1);">
    <div class="container">
        <a class="navbar-brand fw-bold" href="/">📓 Catatan</a>

        <div class="ms-auto">
            <?php if ($this->dispatcher->getControllerName() === 'notes') { ?>
                <a href="/logout" class="btn btn-danger btn-sm">
                    Logout
                </a>
            <?php } ?>
        </div>
    </div>
</nav>

<div class="container my-4">
    <?= $this->getContent() ?>
</div>

</body>
</html>
